# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        media.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/media'
        originalMedia.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/originalMedia'
        thumbnail.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/thumbnail'
when@test:
    flysystem:
        storages:
            media.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/test/storage/media'
            filteredMedia.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/test/storage/filteredMedia'
            thumbnail.storage:
                adapter: 'local'
                options:
                    directory: '%kernel.project_dir%/var/test/storage/thumbnail'
