vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
        media:
            uri_prefix: /vich
            upload_destination: originalMedia.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\PropertyDirectoryNamer
                options: { property: 'vichDirectoryName', transliterate: false }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
