<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration Symfony 8.1 / Doctrine ORM 3 / DBAL 4.
 *
 * Sur PostgreSQL, ORM 3 abandonne les colonnes auto-incrémentées SERIAL
 * (séquence + DEFAULT nextval) au profit des colonnes IDENTITY
 * (GENERATED BY DEFAULT AS IDENTITY).
 *
 * Pour chaque table, la conversion se fait en 4 temps afin de fonctionner
 * aussi bien sur une base vide que peuplée :
 *   1. retrait du DEFAULT existant ;
 *   2. suppression de l'ancienne séquence SERIAL ;
 *   3. déclaration de la colonne en IDENTITY ;
 *   4. réalignement de la séquence interne sur MAX(id)+1 (évite les collisions
 *      d'id sur les tables déjà peuplées).
 *
 * Les COMMENT ON COLUMN vidés correspondent à la suppression des commentaires
 * de type DC2Type, devenus inutiles avec DBAL 4 (typage natif).
 */
final class Version20260628112401 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Symfony 8.1 / Doctrine ORM 3 : conversion des colonnes id SERIAL -> IDENTITY (PostgreSQL).';
    }

    public function up(Schema $schema): void
    {
        // link
        $this->addSql('ALTER TABLE link ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS link_id_seq');
        $this->addSql('ALTER TABLE link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('link', 'id'), COALESCE((SELECT MAX(id) FROM link), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN link.created_at IS \'\'');

        // media
        $this->addSql('ALTER TABLE media ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS media_id_seq');
        $this->addSql('ALTER TABLE media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('media', 'id'), COALESCE((SELECT MAX(id) FROM media), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN media.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN media.uploaded_at IS \'\'');

        // project
        $this->addSql('ALTER TABLE project ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS project_id_seq');
        $this->addSql('ALTER TABLE project ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('project', 'id'), COALESCE((SELECT MAX(id) FROM project), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN project.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN project.share_started_at IS \'\'');

        // user (mot réservé -> identifiant entre guillemets)
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS user_id_seq');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('\"user\"', 'id'), COALESCE((SELECT MAX(id) FROM \"user\"), 0) + 1, false)");
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');

        // messenger_messages (table de transport Messenger)
        $this->addSql('DROP INDEX idx_75ea56e0e3bd61ce');
        $this->addSql('DROP INDEX idx_75ea56e0fb7336f0');
        $this->addSql('DROP INDEX idx_75ea56e016ba31db');
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql("SELECT setval(pg_get_serial_sequence('messenger_messages', 'id'), COALESCE((SELECT MAX(id) FROM messenger_messages), 0) + 1, false)");
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // Retour à des colonnes SERIAL : suppression de l'IDENTITY, recréation
        // d'une séquence et du DEFAULT nextval, réalignée sur MAX(id)+1.
        $this->downSerial('link', 'link_id_seq');
        $this->addSql('COMMENT ON COLUMN link.created_at IS \'(DC2Type:datetime_immutable)\'');

        $this->downSerial('media', 'media_id_seq');
        $this->addSql('COMMENT ON COLUMN media.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN media.uploaded_at IS \'(DC2Type:datetime_immutable)\'');

        $this->downSerial('project', 'project_id_seq');
        $this->addSql('COMMENT ON COLUMN project.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN project.share_started_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('CREATE SEQUENCE IF NOT EXISTS user_id_seq');
        $this->addSql("SELECT setval('user_id_seq', COALESCE((SELECT MAX(id) FROM \"user\"), 0) + 1, false)");
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\')');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('DROP INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750');
        $this->downSerial('messenger_messages', 'messenger_messages_id_seq');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
    }

    /**
     * Reconvertit une colonne id IDENTITY en SERIAL (séquence + DEFAULT).
     */
    private function downSerial(string $table, string $sequence): void
    {
        $this->addSql(sprintf('ALTER TABLE %s ALTER id DROP IDENTITY IF EXISTS', $table));
        $this->addSql(sprintf('CREATE SEQUENCE IF NOT EXISTS %s', $sequence));
        $this->addSql(sprintf("SELECT setval('%s', COALESCE((SELECT MAX(id) FROM %s), 0) + 1, false)", $sequence, $table));
        $this->addSql(sprintf("ALTER TABLE %s ALTER id SET DEFAULT nextval('%s')", $table, $sequence));
    }
}
